=== JanPfenning/whatsMyNextProject/be/src/dtd/details.dtd
<!ELEMENT dataset (Projekt,BackgroundURL)>
<!ELEMENT Projekt (ProjektID,GruppeID,ProjektName,Werkzeugliste?,Materialliste?,Wertliste,Tagliste?,Kommentarliste?,Bewertungliste,Nutzer,Kurzbeschreibung?,Beschreibung,DatumErstellt,DatumErneuert,BildURL)>
<!ELEMENT ProjektID (#PCDATA)>
<!ELEMENT GruppeID (#PCDATA)>
<!ELEMENT ProjektName (#PCDATA)>
<!ELEMENT Werkzeugliste (Werkzeug)*>
<!ELEMENT Werkzeug (Name,Beschreibung)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Beschreibung (#PCDATA)>
<!ELEMENT Materialliste (Material)>
<!ELEMENT Material (Name,Beschreibung,Menge,Einheit)>
<!ELEMENT Menge (#PCDATA)>
<!ELEMENT Einheit (#PCDATA)>
<!ELEMENT Wertliste (Wert1,Wert2,Wert3,Wert4,Wert5,Wert6)>
<!ELEMENT Wert1 (#PCDATA)>
<!ELEMENT Wert2 (#PCDATA)>
<!ELEMENT Wert3 (#PCDATA)>
<!ELEMENT Wert4 (#PCDATA)>
<!ELEMENT Wert5 (#PCDATA)>
<!ELEMENT Wert6 (#PCDATA)>
<!ELEMENT Tagliste (Tag)*>
<!ELEMENT Tag (TagName)>
<!ELEMENT TagName (#PCDATA)>
<!ELEMENT Kommentarliste (KommentarView)*>
<!ELEMENT KommentarView (Inhalt,DatumErstellt,Nick)>
<!ELEMENT Inhalt (#PCDATA)>
<!ELEMENT DatumErstellt (#PCDATA)>
<!ELEMENT Nick (#PCDATA)>
<!ELEMENT Bewertungliste (Stern1,Stern2,Stern3,Stern4,Stern5)>
<!ELEMENT Stern1 (#PCDATA)>
<!ELEMENT Stern2 (#PCDATA)>
<!ELEMENT Stern3 (#PCDATA)>
<!ELEMENT Stern4 (#PCDATA)>
<!ELEMENT Stern5 (#PCDATA)>
<!ELEMENT Nutzer (Nick)>
<!ELEMENT Kurzbeschreibung (#PCDATA)>
<!ELEMENT DatumErneuert (#PCDATA)>
<!ELEMENT BildURL (#PCDATA)>
<!ELEMENT BackgroundURL (#PCDATA)>

=== JanPfenning/whatsMyNextProject/be/src/xml/details2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="application/xml" href="../../../fe/xslt/detail.xsl"?>
<!DOCTYPE dataset SYSTEM "https://expensive.click/be/src/dtd/details.dtd">
<dataset xmlns="http://expensive.click/be/src/dtd/details.dtd">
    <Projekt>
        <ProjektID>2</ProjektID>
        <GruppeID>1</GruppeID>
        <ProjektName>Big Data verarbeiten</ProjektName>
        <Werkzeugliste>
            <Werkzeug>
                <Name>Python</Name>
                <Beschreibung>beißt nicht</Beschreibung>
            </Werkzeug>
            <Werkzeug>
                <Name>IDE</Name>
                <Beschreibung>Integrierte Entwicklungsumgebung</Beschreibung>
            </Werkzeug>
        </Werkzeugliste>
        <Materialliste>
            <Material>
                <Name>Computer</Name>
                <Beschreibung></Beschreibung>
                <Menge>1</Menge>
                <Einheit>Stück</Einheit>
            </Material>
        </Materialliste>
        <Wertliste>
            <Wert1>7</Wert1>
            <Wert2>5</Wert2>
            <Wert3>0</Wert3>
            <Wert4>7</Wert4>
            <Wert5>1</Wert5>
            <Wert6>5</Wert6>
        </Wertliste>
        <Tagliste>
            <Tag>
                <TagName>Programmieren</TagName>
            </Tag>
        </Tagliste>
        <Kommentarliste>
            <KommentarView>
                <Inhalt>
                    Damgeschön für diezes tollen Projekt. Meinen Kindern sehr freuen haben das eszen.
                </Inhalt>
                <DatumErstellt>2020-05-29</DatumErstellt>
                <Nick>xXxPuzzySlayerxXx</Nick>
            </KommentarView>
            <KommentarView>
                <Inhalt>
                    Nachträgliche Rezension: Nachdem ich diese vorzügliche Gericht verzehrt habe, habe ich plötzlich die Fähigkeit erlangt mich angemessen zu artikulieren. Vielen Dank!
                </Inhalt>
                <DatumErstellt>2020-05-30</DatumErstellt>
                <Nick>xXxPuzzySlayerxXx</Nick>
            </KommentarView>
        </Kommentarliste>
        <Bewertungliste>
            <Stern1>0</Stern1>
            <Stern2>0</Stern2>
            <Stern3>0</Stern3>
            <Stern4>0</Stern4>
            <Stern5>0</Stern5>
        </Bewertungliste>
        <Nutzer>
            <Nick>Admin</Nick>
        </Nutzer>
        <Kurzbeschreibung>Ein Projekt, um gesammelte Daten sinnvoll darzustellen.</Kurzbeschreibung>
        <Beschreibung>https://www.btelligent.com/blog/python-module-fuer-data-science/</Beschreibung>
        <DatumErstellt>2020-07-15</DatumErstellt>
        <DatumErneuert>2020-07-15</DatumErneuert>
        <BildURL></BildURL>
    </Projekt>
    <BackgroundURL>./../../../fe/img/1/programmieren.jpg</BackgroundURL>
</dataset>
