=== JanPfenning/whatsMyNextProject/be/src/dtd/groups.dtd
<!ELEMENT dataset (Gruppen,BackgroundURL)>
<!ELEMENT Gruppen (Gruppe)*>
<!ELEMENT Gruppe (GruppeID,BereichID,GruppeName)*>
<!ELEMENT GruppeID (#PCDATA)>
<!ELEMENT BereichID (#PCDATA)>
<!ELEMENT GruppeName (#PCDATA)>
<!ELEMENT BackgroundURL (#PCDATA)>

=== JanPfenning/whatsMyNextProject/be/src/xml/groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../fe/xslt/groupSelection.xsl"?>
<!DOCTYPE dataset SYSTEM "http://localhost:63342/meinCraft/be/src/dtd/groups.dtd">
<dataset xmlns="http://localhost:63342/meinCraft/be/src/dtd/groups.dtd">
    <Gruppen>
        <Gruppe>
            <GruppeID>1</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Spielerisch</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>2</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Einsteiger</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>3</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Fortgeschritten</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>4</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Noob</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>5</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Informativ</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>6</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Günstig</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>6</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Günstig</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>6</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Günstig</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>6</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Günstig</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>6</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Günstig</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>6</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Günstig</GruppeName>
        </Gruppe>
        <Gruppe>
            <GruppeID>6</GruppeID>
            <BereichID>1</BereichID>
            <GruppeName>Günstig</GruppeName>
        </Gruppe>
    </Gruppen>
    <BackgroundURL>
        ../../../fe/img/landingPage.png
    </BackgroundURL>
</dataset>
