=== JanPfenning/whatsMyNextProject/be/src/dtd/projects.dtd
<!DOCTYPE dataset [
        <!ELEMENT dataset (Projekte)*>
        <!ELEMENT Projekte (ProjektView)*>
        <!ELEMENT ProjektView (ProjektID|GruppeID|ProjektName|Kurzbeschreibung)*>
        <!ELEMENT ProjektID (#PCDATA)>
        <!ELEMENT GruppeID (#PCDATA)>
        <!ELEMENT ProjektName (#PCDATA)>
        <!ELEMENT Kurzbeschreibung (#PCDATA)>
        ]>

=== JanPfenning/whatsMyNextProject/be/src/xml/projects.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../fe/xslt/overview.xsl"?>
<!DOCTYPE dataset SYSTEM "http://expensive.click/be/src/dtd/projects.dtd">
<dataset xmlns="http://expensive.click/be/src/dtd/projects.dtd">
    <Projekte>
        <ProjektView>
            <ProjektID>1</ProjektID>
            <GruppeID>1</GruppeID>
            <ProjektName>Nudeln kochen</ProjektName>
            <Kurzbeschreibung>man kocht nudeln</Kurzbeschreibung>
        </ProjektView>
        <ProjektView>
            <ProjektID>2</ProjektID>
            <GruppeID>1</GruppeID>
            <ProjektName>Projektmanagement</ProjektName>
            <Kurzbeschreibung>Managen von Projekten</Kurzbeschreibung>
        </ProjektView>
        <ProjektView>
            <ProjektID>4</ProjektID>
            <GruppeID>1</GruppeID>
            <ProjektName>Schlafen</ProjektName>
            <Kurzbeschreibung>selbsterkl√§rend</Kurzbeschreibung>
        </ProjektView>
        <ProjektView>
            <ProjektID>5</ProjektID>
            <GruppeID>1</GruppeID>
            <ProjektName>Nudeln kochen 2</ProjektName>
            <Kurzbeschreibung>man kocht nudeln</Kurzbeschreibung>
        </ProjektView>
        <ProjektView>
            <ProjektID>3</ProjektID>
            <GruppeID>1</GruppeID>
            <ProjektName>Hello World</ProjektName>
            <Kurzbeschreibung>
                Der einfachste Weg um der Welt mal eben Hallo zu sagen
            </Kurzbeschreibung>
        </ProjektView>
    </Projekte>
</dataset>
