=== JanPfenning/whatsMyNextProject/be/src/dtd/topics.dtd
<!ELEMENT dataset (Bereiche|BackgroundURL)*>
<!ELEMENT Bereiche (Bereich)*>
<!ELEMENT Bereich (BereichID|BereichName)*>
<!ELEMENT BereichID (#PCDATA)>
<!ELEMENT BereichName (#PCDATA)>
<!ELEMENT BackgroundURL (#PCDATA)>

=== JanPfenning/whatsMyNextProject/be/src/xml/topics.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../fe/xslt/topicSelection.xsl"?>
<!DOCTYPE dataset SYSTEM "http://localhost:63342/meinCraft/be/src/dtd/topics.dtd">
<dataset xmlns="http://localhost:63342/meinCraft/be/src/dtd/topics.dtd">
    <Bereiche>
        <Bereich>
            <BereichID>1</BereichID>
            <BereichName>Programmieren</BereichName>
        </Bereich>
        <Bereich>
            <BereichID>2</BereichID>
            <BereichName>Handwerk</BereichName>
        </Bereich>
        <Bereich>
            <BereichID>3</BereichID>
            <BereichName>Basteln</BereichName>
        </Bereich>
    </Bereiche>
    <BackgroundURL>
        ../../../fe/img/toolsBackground.jpeg
    </BackgroundURL>
</dataset>
